# .goreleaser.yml

builds:
  # You can have multiple builds defined as a yaml list
  -
    id: "hydra-test"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64